export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INCREMENT_BY_AMOUNT = "INCREMENT_BY_AMOUNT";
export const DECREMENT_BY_AMOUNT = "DECREMENT_BY_AMOUNT";

export const ADD_CONSULTATION = "ADD_CONSULTATION";

export const SET_STATUS_FOR_FILTER = "SET_STATUS_FOR_FILTER";

export const SET_STAGE_FOR_STORE = "SET_STAGE_FOR_STORE";
